language: go
matrix:
  include:
    - go: 1.5.4
      env: GO15VENDOREXPERIMENT=1
    - go: 1.6.2
    - go: tip
  allow_failures:
    - go: tip

script:
 - ./test

notifications:
  email: false

sudo: false
